apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subsonic-data
  namespace: subsonic
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subsonic-music
  namespace: subsonic
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
